client = wilib.loginByToken("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvYW5nIiwicm9sZSI6MCwiY29tcGFueSI6IkkyRyIsImlhdCI6MTU1OTcyOTgyMiwiZXhwIjoxNTU5OTAyNjIyfQ.9zNhQwOQ3obhSjBq6MO3I9QyXVADckywTdyJdLgBs6Y")

print(client.getListProject())